version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:80"
    restart: always

