version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ./server
    volumes:
      - ./server:/app
    networks:
      - app_network

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
